In [43]:
from datasets import load_dataset

ds = load_dataset("TIGER-Lab/MMLU-Pro")

file = open("info/datapath.txt", "r")
data_path = file.read()
file.close()

In [62]:
import pandas as pd

# 특정 스플릿 선택 (예: train 스플릿)
testds = ds["test"]

# pandas DataFrame으로 변환
mmlupro = testds.to_pandas()

mmlupro = mmlupro[["question", "options", 'answer', 'category']]
mmlupro

,question,options,answer,category
0,"Typical advertising regulatory bodies suggest,...","[Safe practices, Fear, Jealousy, Trivial, Unsa...",I,business
1,Managers are entrusted to run the company in t...,"[Shareholders, Diligence, Self-interest, Share...",F,business
2,There are two main issues associated with ____...,"[Down, Autonomy, Remuneration, Benefit, Down, ...",J,business
3,_______ locate morality beyond the sphere of r...,"[Ethical egoism, Ethics of duty, Postmodern et...",C,business
4,Some of key differences between Islamic finan...,"[Interest, Certain, Assured, Both tangible and...",G,business
...,...,...,...,...
12027,A hot mild steel rod is placed in a carbonaceo...,"[2.2 hr, 0.75 hr, 1.5 hr, 6.0 hr, 4.5 hr, 0.30...",J,engineering
12028,The cost of making the correct decisions for t...,"[(a) Decision made is d_1, (b) Decision d_1, (...",H,engineering
12029,Consider the evaporation of liquid ammonia int...,"[110 lb moles/hr-ft^2-atm, 200 lb moles/hr-ft^...",F,engineering
12030,"Air (100°F, 1atm) is flowing at a velocity of ...",[Local convective heat transfer coefficient: 1...,I,engineering
12031,The frequency range of a commercially broadcas...,"[110%, 125%, 50%, 62.5%, 75%, 83.3%, 93.8%, 57...",F,engineering

In [77]:
# 원하는 토픽 지정 !!!!!!!!!!!!!!!
topic = 'business'
mmlupro_select = mmlupro[mmlupro['category']==topic]
mmlupro_select.reset_index(drop=True, inplace=True) # 인덱스 초기화
mmlupro_select['quesNum'] = None
for idx in range(len(mmlupro_select)) : mmlupro_select.loc[idx, 'quesNum'] = f'QUESTION{idx}) '
mmlupro_select

/tmp/ipykernel_420257/433725126.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mmlupro_select['quesNum'] = None

,question,options,answer,category,quesNum
0,"Typical advertising regulatory bodies suggest,...","[Safe practices, Fear, Jealousy, Trivial, Unsa...",I,business,QUESTION0)
1,Managers are entrusted to run the company in t...,"[Shareholders, Diligence, Self-interest, Share...",F,business,QUESTION1)
2,There are two main issues associated with ____...,"[Down, Autonomy, Remuneration, Benefit, Down, ...",J,business,QUESTION2)
3,_______ locate morality beyond the sphere of r...,"[Ethical egoism, Ethics of duty, Postmodern et...",C,business,QUESTION3)
4,Some of key differences between Islamic finan...,"[Interest, Certain, Assured, Both tangible and...",G,business,QUESTION4)
...,...,...,...,...,...
784,Assuming that each lived for the term of the p...,"[$3649 and $2207, $2207 and $5000, $110.35 and...",H,business,QUESTION784)
785,The following entries appeared in the ledgers ...,"[4 times, 6 times, 2 times, 3 times, 4.5 times...",A,business,QUESTION785)
786,The Experimental Company is now producing and ...,"[$258.00, $259.50/unit, $253.00/unit, $257.50,...",D,business,QUESTION786)
787,Robert Rogers is a real estate salesman whose ...,"[$8,967.88, $2,586.84, $7,381.04, $9,217.88, $...",C,business,QUESTION787)
788,Mr. Darnell purchased 20 shares of American Te...,"[$11.00 per share, total loss $220.00, $14.25 ...",J,business,QUESTION788)

In [78]:
# 알파벳을 붙이는 작업
for idx in range(len(mmlupro_select)) : 


    mmlupro_select.at[idx, 'options'] = [(f"({chr(65 + i)}) {item}") for i, item in enumerate(mmlupro_select['options'][idx])]
    mmlupro_select.at[idx, 'options'] = '\n'.join(mmlupro_select['options'][idx])

# 출력 확인
mmlupro_select

,question,options,answer,category,quesNum
0,"Typical advertising regulatory bodies suggest,...","(A) Safe practices, Fear, Jealousy, Trivial\n(...",I,business,QUESTION0)
1,Managers are entrusted to run the company in t...,"(A) Shareholders, Diligence, Self-interest\n(B...",F,business,QUESTION1)
2,There are two main issues associated with ____...,"(A) Down, Autonomy, Remuneration, Benefit\n(B)...",J,business,QUESTION2)
3,_______ locate morality beyond the sphere of r...,(A) Ethical egoism\n(B) Ethics of duty\n(C) Po...,C,business,QUESTION3)
4,Some of key differences between Islamic finan...,"(A) Interest, Certain, Assured, Both tangible ...",G,business,QUESTION4)
...,...,...,...,...,...
784,Assuming that each lived for the term of the p...,(A) $3649 and $2207\n(B) $2207 and $5000\n(C) ...,H,business,QUESTION784)
785,The following entries appeared in the ledgers ...,(A) 4 times\n(B) 6 times\n(C) 2 times\n(D) 3 t...,A,business,QUESTION785)
786,The Experimental Company is now producing and ...,"(A) $258.00, $259.50/unit, $253.00/unit\n(B) $...",D,business,QUESTION786)
787,Robert Rogers is a real estate salesman whose ...,"(A) $8,967.88, $2,586.84, $7,381.04\n(B) $9,21...",C,business,QUESTION787)
788,Mr. Darnell purchased 20 shares of American Te...,"(A) $11.00 per share, total loss $220.00\n(B) ...",J,business,QUESTION788)

In [79]:
mmlupro_select["prompts"] = mmlupro_select['quesNum'] + mmlupro_select["question"] + "\n" + mmlupro_select["options"]
# 큰따옴표 제거 (혹시나)
mmlupro_select = mmlupro_select.replace("\"", "\'", regex=True)
#csv로 저장
mmlupro_select = mmlupro_select.rename(columns={'answer': 'answers'})
mmlupro_select[['prompts', 'answers']].to_csv(data_path+f'mmlupro_test_{topic}.csv', index = False, sep=',')

/tmp/ipykernel_420257/3524260579.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mmlupro_select["prompts"] = mmlupro_select['quesNum'] + mmlupro_select["question"] + "\n" + mmlupro_select["options"]